In [199]:
import numpy as np

In [200]:
r = 3

In [201]:
#mat = np.array([[8,1,6],[7,2,0],[7,7,6]])
mat = np.random.randint(0,11,r*r).reshape(r,r)
original_mat = mat.copy()
original_mat

array([[ 1,  8, 10],
       [ 5,  4,  8],
       [ 5,  0,  0]])

In [202]:
row_min = np.min(mat,axis=1,keepdims=True)
mat = mat - row_min
mat

array([[0, 7, 9],
       [1, 0, 4],
       [5, 0, 0]])

In [203]:
col_min = np.min(mat,axis=0,keepdims=False)
mat = mat - col_min
mat

array([[0, 7, 9],
       [1, 0, 4],
       [5, 0, 0]])

In [204]:
rank = np.linalg.matrix_rank(mat)
rank

3

In [205]:
#Getting individual rows and columns
result_1 = zero_indices(mat)
result_1
print("Indices of rows and columns with a single zero:", result_1)

ans = addition(result_1,original_mat)
print(f"Result from brute method : {ans}")
ans_2 = using_lib(original_mat)
print(f"Result from scipy : {ans_2}")
if ans == ans_2:
    print("Both results match.")


Indices of rows and columns with a single zero: [(0, 0), (1, 1), (2, 2)]
Result from brute method : 5
Result from scipy : 5
Both results match.


In [206]:
def zero_indices(mat,eli_rows=None,eli_cols=None,result=None):
    if eli_rows is None:
        eli_rows = set()
    if eli_cols is None:
        eli_cols = set()
    if result is None:
        result = []
    r = mat.shape[0]
    c = mat.shape[1]
    f = False #Flag to check if new single zero rows/cols are found
    for i in range(r):
        if i in eli_rows:
            continue
        zero_pos = np.where(mat[i] == 0)[0] #gets column where zero is present
        zero_pos = [z for z in zero_pos if z not in eli_cols]

        if len(zero_pos) == 1:
            col_index = zero_pos[0] #Getting index of column
            result.append((i,col_index)) #Storing a tuple
            eli_rows.add(i)
            eli_cols.add(col_index)
            f = True
        
    #DOing the same for columns
    for j in range(c):
        if j in eli_cols:
            continue
        zero_pos = np.where(mat[:,j] == 0)[0]
        zero_pos = [z for z in zero_pos if z not in eli_rows]

        if len(zero_pos) == 1:
            row_index = zero_pos[0]
            result.append((row_index,j)) #Storing a tuple
            eli_rows.add(row_index)
            eli_cols.add(j)
            f = True
    if f:
        return result
    

In [207]:
def addition(result,original_mat):
    total = sum(original_mat[row,col] for row,col in result)
    return total
    

In [208]:
#Using scipy
from scipy.optimize import linear_sum_assignment
def using_lib(original_mat):
    row_ind, col_ind = linear_sum_assignment(original_mat)
    return original_mat[row_ind, col_ind].sum()